Insert into country (name) Values ('USA')

INSERT into state (name, country_id) VALUES ('Puerto Rico',1),
('Virgin Islands',1),
('Massachusetts',1),
('Rhode Island',1),
('New Hampshire',1),
('Maine',1),
('Vermont',1),
('Connecticut',1),
('New York',1),
('New Jersey',1),
('Pennsylvania',1),
('Delaware',1),
('District of Columbia',1),
('Virginia',1),
('Maryland',1),
('West Virginia',1),
('North Carolina',1),
('South Carolina',1),
('Georgia',1),
('Florida',1),
('Alabama',1),
('Tennessee',1),
('Mississippi',1),
('Kentucky',1),
('Ohio',1),
('Indiana',1),
('Michigan',1),
('Iowa',1),
('Wisconsin',1),
('Minnesota',1),
('South Dakota',1),
('North Dakota',1),
('Montana',1),
('Illinois',1),
('Missouri',1),
('Kansas',1),
('Nebraska',1),
('Louisiana',1),
('Arkansas',1),
('Oklahoma',1),
('Texas',1),
('Colorado',1),
('Wyoming',1),
('Idaho',1),
('Utah',1),
('Arizona',1),
('New Mexico',1),
('Nevada',1),
('California',1),
('Hawaii',1),
('American Samoa',1),
('Guam',1),
('Northern Mariana Islands',1),
('Oregon',1),
('Washington',1),
('Alaska',1);
